# Generated by Django 4.0 on 2021-12-29 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post_0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=30, verbose_name='ФИО')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('post_head', models.CharField(default='none', max_length=50, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Дата приема')),
                ('wages', models.IntegerField(verbose_name='Зарплата')),
                ('total_paid', models.IntegerField(verbose_name='Всего выплачено')),
            ],
            options={
                'verbose_name': 'ген. деиректора',
                'verbose_name_plural': 'Level 0 - ген. директор',
            },
        ),
        migrations.CreateModel(
            name='Post_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=30, verbose_name='ФИО')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Дата приема')),
                ('wages', models.IntegerField(verbose_name='Зарплата')),
                ('total_paid', models.IntegerField(verbose_name='Всего выплачено')),
                ('post_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.post_0', verbose_name='Начальник')),
            ],
            options={
                'verbose_name': 'Директора',
                'verbose_name_plural': 'Level 1 - директор',
            },
        ),
        migrations.CreateModel(
            name='Post_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=30, verbose_name='ФИО')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Дата приема')),
                ('wages', models.IntegerField(verbose_name='Зарплата')),
                ('total_paid', models.IntegerField(verbose_name='Всего выплачено')),
                ('post_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.post_1', verbose_name='Начальник')),
            ],
            options={
                'verbose_name': 'главные менеджеры',
                'verbose_name_plural': 'Level 2 - главный менеджер',
            },
        ),
        migrations.CreateModel(
            name='Post_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=30, verbose_name='ФИО')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Дата приема')),
                ('wages', models.IntegerField(verbose_name='Зарплата')),
                ('total_paid', models.IntegerField(verbose_name='Всего выплачено')),
                ('post_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.post_2', verbose_name='Начальник')),
            ],
            options={
                'verbose_name': 'младшие менеджеры',
                'verbose_name_plural': 'Level 3 - младший менеджер',
            },
        ),
        migrations.CreateModel(
            name='Post_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=30, verbose_name='ФИО')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Дата приема')),
                ('wages', models.IntegerField(verbose_name='Зарплата')),
                ('total_paid', models.IntegerField(verbose_name='Всего выплачено')),
                ('post_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.post_3', verbose_name='Начальник')),
            ],
            options={
                'verbose_name': 'консультанты',
                'verbose_name_plural': 'Level 4 - консультант',
            },
        ),
        migrations.CreateModel(
            name='Post_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=30, verbose_name='ФИО')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Дата приема')),
                ('wages', models.IntegerField(verbose_name='Зарплата')),
                ('total_paid', models.IntegerField(verbose_name='Всего выплачено')),
                ('post_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.post_4', verbose_name='Начальник')),
            ],
            options={
                'verbose_name': 'стажеры',
                'verbose_name_plural': 'Level 5 - стажер',
            },
        ),
    ]
