# Generated by Django 3.2.10 on 2022-01-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_0',
            options={'verbose_name': 'Level 0', 'verbose_name_plural': 'Level 0'},
        ),
        migrations.AlterModelOptions(
            name='post_1',
            options={'verbose_name': 'Level 1', 'verbose_name_plural': 'Level 1'},
        ),
        migrations.AlterModelOptions(
            name='post_2',
            options={'verbose_name': 'Level 2', 'verbose_name_plural': 'Level 2'},
        ),
        migrations.AlterModelOptions(
            name='post_3',
            options={'verbose_name': 'Level 3', 'verbose_name_plural': 'Level 3'},
        ),
        migrations.AlterModelOptions(
            name='post_4',
            options={'verbose_name': 'Level 4', 'verbose_name_plural': 'Level 4'},
        ),
        migrations.AlterModelOptions(
            name='post_5',
            options={'verbose_name': 'Level 5', 'verbose_name_plural': 'Level 5'},
        ),
        migrations.AlterField(
            model_name='post_0',
            name='post_head',
            field=models.CharField(default='none', max_length=50, verbose_name='Начальник'),
        ),
    ]
